#!/usr/bin/python

# from http://sontek.net/blog/detail/tips-and-tricks-for-the-python-interpreter

import sys
import os
from code import InteractiveConsole
from tempfile import mkstemp
import pprint


# tab completion
try:
    import readline
except ImportError:
    print("Module readline not available.")
else:
    import rlcompleter
    readline.parse_and_bind("tab: complete")


# custom prompt
class Prompt:
    def __init__(self, str='>>>'):
        self.str = str;

    def __str__(self):
        return self.str

sys.ps1 = Prompt("\033[31m > \033[0m")


# enable pretty printing for stdout
def my_displayhook(value):
    if value is not None:
        try:
            import __builtin__
            __builtin__._ = value
        except ImportError:
            __builtins__._ = value

        pprint.pprint(value)

sys.displayhook = my_displayhook


# load up vim to edit lines of code from the interpreter
EDITOR = os.environ.get('EDITOR', 'vi')
EDIT_CMD = '\e'
sys.stdout.write('\nedit code with \e\n')

class EditableBufferInteractiveConsole(InteractiveConsole):
    def __init__(self, *args, **kwargs):
        self.last_buffer = [] # this holds the last executed statement
        InteractiveConsole.__init__(self, *args, **kwargs)

    def runsource(self, source, *args):
        self.last_buffer = [ source.encode('latin-1') ]
        return InteractiveConsole.runsource(self, source, *args)

    def raw_input(self, *args):
        line = InteractiveConsole.raw_input(self, *args)
        if line == EDIT_CMD:
            fd, tmpfl = mkstemp('.py')
            os.write(fd, b'\n'.join(self.last_buffer))
            os.close(fd)
            os.system('%s %s' % (EDITOR, tmpfl))
            line = open(tmpfl).read()
            os.unlink(tmpfl)
            tmpfl = ''
            lines = line.split( '\n' )
            for i in range(len(lines) - 1): self.push( lines[i] )
            line = lines[-1]
        return line

c = EditableBufferInteractiveConsole(locals=locals())
c.interact(banner='')

# exit the python shell on exiting the interactiveconsole
sys.exit()
